# Generated by Django 5.2.5 on 2025-08-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='options',
            table=None,
        ),
    ]
