# Generated by Django 5.2.5 on 2025-09-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('surname', models.CharField(max_length=100, verbose_name='Post Nom')),
                ('firstname', models.CharField(max_length=100, verbose_name='Prenom')),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Feminin')], default='masculin', max_length=10, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name="Niveau d'etude")),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domaine')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_members', to='staff.role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fonctionnaire',
                'verbose_name_plural': 'fonctionnaires',
                'db_table': 'staff',
                'ordering': ['role', 'name'],
            },
        ),
    ]
