# Generated by Django 5.2.5 on 2025-09-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Monsieur'), ('Mme.', 'Madame'), ('Mlle.', 'Mademoiselle'), ('Me.', 'Maitre'), ('Dr.', 'Docteur'), ('Pr.', 'Professeur')], max_length=60, null=True, verbose_name='Titre'),
        ),
    ]
