# Generated by Django 5.2.5 on 2025-09-10 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('staff', '0002_staff_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name'], 'verbose_name': 'fonctionnaire', 'verbose_name_plural': 'fonctionnaires'},
        ),
        migrations.AddField(
            model_name='staff',
            name='admin',
            field=models.BooleanField(default=False, null=True, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de nommination')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin mandat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(blank=True, to='education.course')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.options')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.section')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name': 'Doyen',
                'verbose_name_plural': 'Doyens',
                'db_table': 'Dean',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ManyToManyField(blank=True, to='staff.role'),
        ),
    ]
