# Generated by Django 5.2.5 on 2025-09-11 14:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_options_staff_admin_staff_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', unique=True, verbose_name='Contact📞'),
        ),
    ]
