# Generated by Django 5.2.5 on 2025-08-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('fees', '0001_initial'),
        ('options', '0002_alter_options_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='options',
        ),
        migrations.AlterModelTable(
            name='fees',
            table=None,
        ),
        migrations.AddField(
            model_name='fees',
            name='classe',
            field=models.ManyToManyField(to='classes.classes'),
        ),
        migrations.AddField(
            model_name='fees',
            name='options',
            field=models.ManyToManyField(to='options.options'),
        ),
    ]
