# Generated by Django 5.2.5 on 2025-09-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Frais')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification')),
                ('classe', models.ManyToManyField(to='education.classes')),
                ('options', models.ManyToManyField(blank=True, to='education.options')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.section')),
            ],
            options={
                'verbose_name': 'frais',
                'verbose_name_plural': 'frais',
                'db_table': 'fees',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('month', models.CharField(choices=[('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre'), ('janvier', 'Janvier'), ('fevrier', 'Fevrier'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin')], max_length=60, verbose_name='Mois')),
                ('type_paiement', models.CharField(choices=[('espece', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire')], default='espece', max_length=20, verbose_name='Type de paiement')),
                ('paid_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiment')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification')),
                ('collector', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.fees')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'caisse',
                'db_table': 'box',
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=60, verbose_name='Mois')),
                ('nbrStudents', models.IntegerField(default=0, verbose_name="Nombre d'élèves")),
                ('total_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total payer')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total frais')),
                ('reste', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Reste à payer')),
                ('statut', models.BooleanField(default=False, verbose_name='Statut')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification')),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.fees')),
            ],
            options={
                'verbose_name': 'Total',
                'db_table': 'total',
            },
        ),
    ]
