# Generated by Django 5.2.5 on 2025-09-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='month',
            field=models.IntegerField(choices=[(1, 'Septembre'), (2, 'Octobre'), (3, 'Novembre'), (4, 'Décembre'), (5, 'Janvier'), (6, 'Février'), (7, 'Mars'), (8, 'Avril'), (9, 'Mai'), (10, 'Juin')], default=1, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='total',
            name='month',
            field=models.IntegerField(choices=[(1, 'Septembre'), (2, 'Octobre'), (3, 'Novembre'), (4, 'Décembre'), (5, 'Janvier'), (6, 'Février'), (7, 'Mars'), (8, 'Avril'), (9, 'Mai'), (10, 'Juin')], default=1, verbose_name='Mois'),
        ),
    ]
