# Generated by Django 5.2.5 on 2025-09-06 13:21

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('image', models.ImageField(null=True, upload_to='about_images/')),
            ],
            options={
                'verbose_name': 'A propo',
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Credit')),
                ('duration', models.CharField(max_length=60, verbose_name='Durée')),
                ('level', models.CharField(max_length=100, null=True, verbose_name='Niveau')),
                ('description', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('condition', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service')),
                ('description', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='service_images/')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Temoin')),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('almni', 'Ancien élève'), ('student', 'Elève'), ('staff', 'cadre')], max_length=60, verbose_name='Role')),
                ('content', tinymce.models.HTMLField(null=True, verbose_name='Temoignage')),
                ('image', models.ImageField(null=True, upload_to='testimonial_images/')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'db_table': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='Actuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('hours', models.TimeField(null=True)),
                ('place', models.CharField(max_length=100, null=True, verbose_name='Lieu')),
                ('category', models.CharField(choices=[('DIV_FESTIVAL', 'Festivals'), ('DIV_THEATRE', 'Théâtre & spectacles'), ('DIV_CINEMA', 'Cinéma & projections'), ('DIV_EXPO', 'Expositions & musées'), ('DIV_MODE', 'Mode & défilés'), ('EDU_CONF', 'Conférences'), ('EDU_ATELIER', 'Ateliers / Workshops'), ('EDU_COURS', 'Cours & Formations'), ('EDU_LIVRE', 'Lancements de livres'), ('BUS_FORUM', 'Forums'), ('BUS_SALON', 'Salons professionnels'), ('BUS_NET', 'Networking'), ('SPO_MATCH', 'Matchs & compétitions'), ('SPO_TOURNOI', 'Tournois'), ('SPO_RANDO', 'Randonnées'), ('SOC_MARIAGE', 'Mariages'), ('SOC_ANNIV', 'Anniversaires'), ('SOC_SOIREE', 'Rencontres & soirées'), ('COM_MANIF', 'Manifestations / Marches'), ('COM_FONDS', 'Collectes de fonds'), ('COM_CARIT', 'Actions caritatives'), ('COM_ASSO', 'Événements associatifs')], default='DIV_FESTIVAL', max_length=255, null=True, verbose_name='Categorie')),
                ('date', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='actuality_images/')),
                ('description', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('facilitator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
                'db_table': 'actuality',
            },
        ),
    ]
