# Generated by Django 5.2.5 on 2025-09-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_2',
            field=models.ImageField(null=True, upload_to='about_images/'),
        ),
    ]
