# Generated by Django 5.2.5 on 2025-09-08 11:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_about_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission',
            field=tinymce.models.HTMLField(null=True, verbose_name='Notre mission'),
        ),
        migrations.AddField(
            model_name='about',
            name='values',
            field=tinymce.models.HTMLField(null=True, verbose_name='Nos valeur'),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=tinymce.models.HTMLField(null=True, verbose_name='Notre vision'),
        ),
    ]
