# Generated by Django 5.2.5 on 2025-09-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_about_mission_about_values_about_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='team',
            field=models.ImageField(null=True, upload_to='about_images/', verbose_name="photo d'equipe"),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='about_images/', verbose_name='photo de batiment'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_2',
            field=models.ImageField(null=True, upload_to='about_images/', verbose_name="photo d'eleves"),
        ),
    ]
