# Generated by Django 5.2.5 on 2025-09-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_about_team_alter_about_image_alter_about_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuality',
            name='end',
            field=models.TimeField(null=True, verbose_name='heure de cloture'),
        ),
        migrations.AlterField(
            model_name='about',
            name='team',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/', verbose_name="photo d'equipe"),
        ),
        migrations.AlterField(
            model_name='actuality',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date et heure'),
        ),
    ]
