# Generated by Django 5.2.5 on 2025-09-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_actuality_end_alter_about_team_alter_actuality_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='actuality',
            name='date',
            field=models.DateTimeField(null=True, verbose_name="date et heure d'ouverture"),
        ),
    ]
