# Generated by Django 5.2.5 on 2025-09-22 10:47

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_delete_service_alter_actuality_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(verbose_name='Adresse')),
                ('hours_operation', tinymce.models.HTMLField(blank=True, verbose_name='Heure de travail')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('message', models.TextField(max_length=500, verbose_name='message')),
                ('video', models.FileField(default='hero/default.mp4', upload_to='hero/')),
                ('open_date', models.DateTimeField(verbose_name="date d'ouverture")),
                ('close_date', models.DateTimeField(verbose_name='date de cloture')),
                ('register_date', models.DateTimeField(verbose_name="date d'inscription")),
            ],
            options={
                'verbose_name': 'Bienvenu',
                'db_table': 'Hero',
            },
        ),
    ]
