# Generated by Django 5.2.5 on 2025-09-23 12:36

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_contact_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', unique=True, verbose_name='Téléphone'),
        ),
    ]
