# Generated by Django 5.2.5 on 2025-08-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('course', '0001_initial'),
        ('options', '0001_initial'),
        ('section', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ManyToManyField(related_name='classe', to='classes.classes')),
                ('course', models.ManyToManyField(related_name='course', to='course.course')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='options.options')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staff')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.section')),
            ],
            options={
                'verbose_name': 'attribution cours',
                'db_table': 'courses',
            },
        ),
    ]
