# Generated by Django 5.2.5 on 2025-08-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('course', '0002_alter_course_table'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'attribution cours'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course',
        ),
        migrations.AlterModelTable(
            name='courses',
            table=None,
        ),
        migrations.AddField(
            model_name='courses',
            name='classe',
            field=models.ManyToManyField(related_name='classe', to='classes.classes'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course',
            field=models.ManyToManyField(related_name='course', to='course.course'),
        ),
    ]
