# Generated by Django 5.2.5 on 2025-08-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pay', models.PositiveIntegerField()),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.staff')),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.fees')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'caisse',
                'db_table': 'box',
            },
        ),
    ]
