# Generated by Django 5.2.5 on 2025-09-06 13:21

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('surname', models.CharField(max_length=60, verbose_name='Post Nom')),
                ('first_name', models.CharField(max_length=60, verbose_name='Prenom')),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], default='masculin', max_length=10, null=True)),
                ('matricule', models.CharField(blank=True, max_length=100, unique=True)),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('place_birthday', models.CharField(blank=True, max_length=60, null=True, verbose_name='Lieu de naissance')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('statut', models.CharField(choices=[('scolariser', 'Scolariser 🟡 '), ('exempter', 'Exempter 🟢')], default='scolariser', max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Père')),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mère')),
                ('garduan', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tuteur')),
                ('contact_garduan', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', unique=True, verbose_name='Contact du tuteur')),
                ('address_garduan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse du Tuteur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.classes')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.options')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.section')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'db_table': 'students',
                'ordering': ['name'],
            },
        ),
    ]
