# Generated by Django 5.2.5 on 2025-08-27 15:36

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('options', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('matricule', models.CharField(blank=True, max_length=100, unique=True)),
                ('date_birthday', models.DateField(blank=True, null=True)),
                ('place_birthday', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('garduan', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_garduan', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='CD', unique=True)),
                ('address_garduan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classes')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='options.options')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.section')),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'db_table': 'students',
                'ordering': ['name'],
            },
        ),
    ]
